-- ============================================================================
-- Awards & Engraving — catalog overrides
--
-- The product catalog itself (10,030 items across 7 Premier Line collections)
-- lives in static JSON under /catalog/, generated by the scraper and refreshed
-- by re-running it — never hand-managed. This table holds ONLY the shop's
-- decisions layered on top of that feed:
--
--   * hidden   — take a collection, group, category or single product OFF the
--                site without touching the feed.
--   * featured — pin a product to the "Featured" row of its collection.
--
-- One row per decision, keyed by a stable ref. Refs:
--   col:<key>                     e.g. col:crystal            (a whole collection)
--   grp:<key>|<group name>        e.g. grp:crystal|Glass Awards
--   cat:<key>:<id>                e.g. cat:crystal:2          (a category)
--   sku:<SKU>                     e.g. sku:CRY048L            (one product)
--
-- The public catalog reads every row and filters the JSON client-side, so the
-- 10k products stay out of the database entirely.
-- ============================================================================

create table if not exists public.catalog_overrides (
  ref         text primary key,               -- see ref scheme above
  hidden      boolean not null default false,
  featured    boolean not null default false,
  label       text,                           -- human note, e.g. the category name (for the admin list)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  updated_by  text
);

drop trigger if exists catalog_overrides_set_updated_at on public.catalog_overrides;
create trigger catalog_overrides_set_updated_at
  before update on public.catalog_overrides
  for each row execute function public.set_updated_at();

alter table public.catalog_overrides enable row level security;

-- Visibility flags are not sensitive: the public site needs every row to know
-- what to hide/feature, so read is open. Writes are admin-only.
drop policy if exists "catalog_overrides public read" on public.catalog_overrides;
create policy "catalog_overrides public read" on public.catalog_overrides
  for select using (true);
drop policy if exists "catalog_overrides admin write" on public.catalog_overrides;
create policy "catalog_overrides admin write" on public.catalog_overrides
  for all to authenticated using (true) with check (true);
